"""add customer_code to picking_audit

Revision ID: a0ce14067b9c
Revises: a37d0c1cb358
Create Date: 2026-03-13 20:15:28.596079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ce14067b9c'
down_revision: Union[str, Sequence[str], None] = 'a37d0c1cb358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picking_audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_code', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picking_audits', schema=None) as batch_op:
        batch_op.drop_column('customer_code')

    # ### end Alembic commands ###
