"""add reconciliation history table

Revision ID: a37d0c1cb358
Revises: cafe460aa43c
Create Date: 2026-03-12 19:50:15.547875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37d0c1cb358'
down_revision: Union[str, Sequence[str], None] = 'cafe460aa43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('archive_date', sa.String(length=50), nullable=False),
    sa.Column('import_reference', sa.String(length=100), nullable=False),
    sa.Column('waybill', sa.String(length=100), nullable=False),
    sa.Column('grn', sa.String(length=100), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('bin_location', sa.String(length=100), nullable=True),
    sa.Column('relocated_bin', sa.String(length=100), nullable=True),
    sa.Column('qty_expected', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_history_archive_date'), ['archive_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_history_country_code'), ['country_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reconciliation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_history_country_code'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_history_archive_date'))

    op.drop_table('reconciliation_history')
    # ### end Alembic commands ###
