"""initial_setup_multicountry

Revision ID: cafe460aa43c
Revises: 
Create Date: 2026-03-01 14:26:23.265381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cafe460aa43c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key', 'country_code')
    )
    op.create_table('count_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('user_username', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.Column('end_time', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('inventory_stage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('count_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_count_sessions_country_code'), ['country_code'], unique=False)

    op.create_table('cycle_count_recordings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('planned_date', sa.String(length=50), nullable=False),
    sa.Column('executed_date', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_description', sa.String(length=255), nullable=True),
    sa.Column('bin_location', sa.String(length=100), nullable=True),
    sa.Column('system_qty', sa.Integer(), nullable=False),
    sa.Column('physical_qty', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('abc_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_count_recordings_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycle_count_recordings_item_code'), ['item_code'], unique=False)

    op.create_table('grn_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('import_reference', sa.String(length=100), nullable=False),
    sa.Column('waybill', sa.String(length=100), nullable=False),
    sa.Column('grn_number', sa.String(length=255), nullable=True),
    sa.Column('packs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lines', sa.String(length=50), nullable=True),
    sa.Column('aaf_date', sa.String(length=50), nullable=True),
    sa.Column('grn1_date', sa.String(length=50), nullable=True),
    sa.Column('aaf_grn1', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('grn3_date', sa.String(length=50), nullable=True),
    sa.Column('grn1_grn3', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('ct', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grn_master_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_grn_master_import_reference'), ['import_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_grn_master_waybill'), ['waybill'], unique=False)

    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('importReference', sa.String(length=100), nullable=False),
    sa.Column('waybill', sa.String(length=100), nullable=True),
    sa.Column('itemCode', sa.String(length=100), nullable=True),
    sa.Column('itemDescription', sa.String(length=255), nullable=True),
    sa.Column('binLocation', sa.String(length=100), nullable=True),
    sa.Column('relocatedBin', sa.String(length=100), nullable=True),
    sa.Column('qtyReceived', sa.Integer(), nullable=True),
    sa.Column('qtyGrn', sa.Integer(), nullable=True),
    sa.Column('difference', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_country_code'), ['country_code'], unique=False)

    op.create_table('master_items',
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('abc_code', sa.String(length=10), nullable=True),
    sa.Column('physical_qty', sa.Integer(), nullable=False),
    sa.Column('bin_1', sa.String(length=100), nullable=True),
    sa.Column('additional_bin', sa.String(length=100), nullable=True),
    sa.Column('weight_per_unit', sa.String(length=50), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('item_class', sa.String(length=50), nullable=True),
    sa.Column('item_group_major', sa.String(length=50), nullable=True),
    sa.Column('stockroom', sa.String(length=50), nullable=True),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sic_code_company', sa.String(length=50), nullable=True),
    sa.Column('sic_code_stockroom', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('item_code', 'country_code')
    )
    with op.batch_alter_table('master_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_items_abc_code'), ['abc_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_items_bin_1'), ['bin_1'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_items_item_code'), ['item_code'], unique=False)

    op.create_table('picking_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('despatch_number', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('packages', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('picking_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_picking_audits_country_code'), ['country_code'], unique=False)

    op.create_table('recount_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('stage_to_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recount_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recount_list_country_code'), ['country_code'], unique=False)

    op.create_table('shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('carrier', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_country_code'), ['country_code'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_approved', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.String(length=500), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.String(length=50), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)

    op.create_table('picking_audit_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('order_line', sa.String(length=50), nullable=True),
    sa.Column('qty_req', sa.Integer(), nullable=False),
    sa.Column('qty_scan', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('edited', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['picking_audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('picking_audit_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_picking_audit_items_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_picking_audit_items_country_code'), ['country_code'], unique=False)

    op.create_table('picking_package_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('package_number', sa.Integer(), nullable=False),
    sa.Column('order_line', sa.String(length=50), nullable=True),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('qty_scan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['picking_audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_picking_package_items_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_picking_package_items_country_code'), ['country_code'], unique=False)

    op.create_table('session_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('closed_at', sa.String(length=50), nullable=True),
    sa.Column('count_stage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['count_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_locations_location_code'), ['location_code'], unique=False)

    op.create_table('shipment_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['picking_audits.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_audits_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_audits_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_audits_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('stock_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_description', sa.String(length=255), nullable=True),
    sa.Column('counted_qty', sa.Integer(), nullable=False),
    sa.Column('counted_location', sa.String(length=100), nullable=False),
    sa.Column('bin_location_system', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['count_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_counts_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_counts_session_id'), ['session_id'], unique=False)

    op.create_table('cycle_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('abc_code', sa.String(length=10), nullable=True),
    sa.Column('count_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['count_id'], ['stock_counts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_counts_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycle_counts_item_code'), ['item_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_counts_item_code'))
        batch_op.drop_index(batch_op.f('ix_cycle_counts_country_code'))

    op.drop_table('cycle_counts')
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_counts_session_id'))
        batch_op.drop_index(batch_op.f('ix_stock_counts_country_code'))

    op.drop_table('stock_counts')
    with op.batch_alter_table('shipment_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_audits_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_audits_country_code'))
        batch_op.drop_index(batch_op.f('ix_shipment_audits_audit_id'))

    op.drop_table('shipment_audits')
    with op.batch_alter_table('session_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_locations_location_code'))

    op.drop_table('session_locations')
    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picking_package_items_country_code'))
        batch_op.drop_index(batch_op.f('ix_picking_package_items_audit_id'))

    op.drop_table('picking_package_items')
    with op.batch_alter_table('picking_audit_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picking_audit_items_country_code'))
        batch_op.drop_index(batch_op.f('ix_picking_audit_items_audit_id'))

    op.drop_table('picking_audit_items')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_country_code'))

    op.drop_table('shipments')
    with op.batch_alter_table('recount_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recount_list_country_code'))

    op.drop_table('recount_list')
    with op.batch_alter_table('picking_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picking_audits_country_code'))

    op.drop_table('picking_audits')
    with op.batch_alter_table('master_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_items_item_code'))
        batch_op.drop_index(batch_op.f('ix_master_items_bin_1'))
        batch_op.drop_index(batch_op.f('ix_master_items_abc_code'))

    op.drop_table('master_items')
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_country_code'))

    op.drop_table('logs')
    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grn_master_waybill'))
        batch_op.drop_index(batch_op.f('ix_grn_master_import_reference'))
        batch_op.drop_index(batch_op.f('ix_grn_master_country_code'))

    op.drop_table('grn_master')
    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_count_recordings_item_code'))
        batch_op.drop_index(batch_op.f('ix_cycle_count_recordings_country_code'))

    op.drop_table('cycle_count_recordings')
    with op.batch_alter_table('count_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_count_sessions_country_code'))

    op.drop_table('count_sessions')
    op.drop_table('app_state')
    # ### end Alembic commands ###
